#!/bin/bash	

rm -rf $1.ko

echo "obj-m	:=	$1.o" > Makefile
make ARCH=arm CROSS_COMPILE=~/bbb/bb-kernel/dl/gcc-linaro-7.3.1-2018.05-x86_64_arm-linux-gnueabihf/bin/arm-linux-gnueabihf- -C /home/sriram/bbb/bb-kernel/KERNEL/ M=`pwd ` modules
